name: Lint
run-name: Lint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # - name: Setup Bun
      #   uses: oven-sh/setup-bun@v1
      - name: Clone repo
        uses: actions/checkout@v4
      # - name: Install dependencies
      #   run: bun install --frozen-lockfile
      # - name: Build
      #   run: bun run build
