name: Publish
run-name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
      - name: Publish reffuse
        uses: JS-DevTools/npm-publish@v3
        with:
          package: packages/reffuse
          token: ${{ secrets.NPM_TOKEN }}
          registry: https://registry.npmjs.org
      - name: Publish @reffuse/extension-lazyref
        uses: JS-DevTools/npm-publish@v3
        with:
          package: packages/extension-lazyref
          token: ${{ secrets.NPM_TOKEN }}
          registry: https://registry.npmjs.org
