name: Publish
run-name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: npm run build
      - name: Publish
        run: |
          npm config set @thilawyn:registry https://git.valverde.cloud/api/packages/thilawyn/npm/
          npm config set -- //git.valverde.cloud/api/packages/thilawyn/npm/:_authToken "${{ vars.NODE_AUTH_TOKEN }}"
          npm publish
