name: Test build
run-name: Test build
on:
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: |
          cd packages/reffuse
          bun run build
      - name: Pack
        run: |
          cd packages/reffuse
          npm pack --dry-run
